@exported import Security
let errSecItemNotFound: OSStatus
let errSecDecode: OSStatus
let errSecAllocate: OSStatus
let errSecDuplicateItem: OSStatus
let errSecParam: OSStatus
let errSecNotAvailable: OSStatus
let errSecAuthFailed: OSStatus
let errSecUnimplemented: OSStatus
let errSecSuccess: OSStatus
let errSecInteractionNotAllowed: OSStatus
